from excepcion import ingresa_numero as test

valor = int(input('Ingresa un numero: '))

test(valor)